;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/common")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/cogre")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/contrib")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/ede")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/eieio")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/semantic")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/semantic/bovine")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/semantic/ctags")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/semantic/symref")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/semantic/tests")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/semantic/wisent")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/speedbar")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/srecode")
;; (add-to-list 'load-path "~/Downloads/cedet/cedet-1.1/tests")
;; (load-file "~/Downloads/cedet/cedet-1.1/common/cedet.el")
;; (global-ede-mode t)
;; (semantic-load-enable-guady-code-helpers)
;; (setq x-max-tooltip-size '(nil . 25))
;; '(global-semantic-idle-summary-mode nil nil (semantic-idle))

(load-file "~/cedet-bzr/cedet/cedet-devel-load.el")
(load-file "~/cedet-bzr/cedet/lisp/cedet/semantic/wisent/wisent.el")
(load-file "~/cedet-bzr/cedet/lisp/cedet/ede/autoconf-edit.el")
(semantic-mode 1)
(global-ede-mode 1)

(provide 'my-cedet-setup)
