(deftheme my-term-theme
  "Created 2012-10-05.")

(custom-theme-set-faces
 'my-term-theme
 '(cursor ((t (:foreground "#1c1c1c" :background "black"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "blue" :inverse-video nil :underline nil :slant normal :weight bold))))
 '(highlight ((t (:background "darkseagreen2"))))
 '(region ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#585858" :background "lightgoldenrod2"))))
 '(shadow ((t (:foreground "grey50"))))
 '(secondary-selection ((t (:background "yellow1"))))
 '(trailing-whitespace ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#d70000" :background "red1"))))
 '(font-lock-builtin-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "dark slate blue"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "brightgreen" :inverse-video nil :underline nil :slant italic :weight normal))))
 '(font-lock-comment-face ((t (:foreground "brightgreen" :inverse-video nil :underline nil :slant italic :weight normal))))
 '(font-lock-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "dark cyan"))))
 '(font-lock-doc-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "VioletRed4"))))
 '(font-lock-function-name-face ((t (:foreground "blue" :inverse-video nil :underline nil :slant normal :weight normal))))
 '(font-lock-keyword-face ((t (:foreground "green" :inverse-video nil :underline nil :slant normal :weight normal))))
 '(font-lock-negation-char-face ((t (:foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight normal))))
 '(font-lock-preprocessor-face ((t (:foreground "brightred" :inverse-video nil :underline nil :slant normal :weight normal))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#af8700"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight bold))))
 '(font-lock-string-face ((t (:foreground "cyan" :inverse-video nil :underline nil :slant normal :weight normal))))
 '(font-lock-type-face ((t (:foreground "yellow" :inverse-video nil :underline nil :slant normal :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "blue" :inverse-video nil :underline nil :slant normal :weight normal))))
 '(font-lock-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "Red1"))))
 '(button ((t (:foreground "RoyalBlue3" :underline t))))
 '(link ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "RoyalBlue3"))))
 '(link-visited ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "magenta4"))))
 '(fringe ((t (:foreground "#585858" :background "grey95"))))
 '(header-line ((t (:weight normal :slant normal :underline t :box (:line-width -1 :color nil :style released-button) :inverse-video nil :foreground "black" :background "grey75"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :family "Sans Serif"))))
 '(mode-line ((t (:weight normal :slant normal :underline nil :box (:line-width -1 :color nil :style released-button) :inverse-video t :foreground "black" :background "grey75"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:weight light :slant normal :underline nil :box (:line-width -1 :color "grey75" :style nil) :inverse-video t :foreground "grey20" :background "grey90"))))
 '(isearch ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "lightskyblue1" :background "magenta3"))))
 '(isearch-fail ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#d75f00" :background "RosyBrown1"))))
 '(lazy-highlight ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#af8700" :background "paleturquoise"))))
 '(match ((t (:background "yellow1"))))
 '(next-error ((t (:background "lightgoldenrod2"))))
 '(query-replace ((t (:background "magenta3" :foreground "lightskyblue1"))))
 '(default ((t (:inherit nil :stipple nil :background "brightblack" :foreground "#808080" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default")))))

(provide-theme 'my-term-theme)
